settings:
  triggerHeight: 50
  worlds: [] # Worlds where the plugin works, empty - all worlds
  teleportLocation:
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0
    world: 'world'

configVersion: 1 # Format version of this file, do not change
